=== h1262216/crazys-wm-mod/Resources/Data/Jobs/job.dtd
<!ELEMENT Job (Description, Performance, Modifiers?, Gains, Config?, Treatment?, Messages?)>
<!ATTLIST Job ShortName CDATA #REQUIRED>

<!ELEMENT Description (#PCDATA)>
<!ELEMENT Config (Filter, Enjoyment)>
<!ATTLIST Config Shift (both|day-only|night-only|full) FreeOnly (0|1) #IMPLIED DefaultImage CDATA #IMPLIED
        Phase (prepare|produce|main|late) #IMPLIED FightingJob (0|1) #IMPLIED BaseWages CDATA #IMPLIED>
<!ELEMENT Filter (#PCDATA)>
<!ELEMENT Enjoyment EMPTY>
<!ATTLIST Enjoyment PrimaryAction CDATA #IMPLIED SecondaryAction CDATA #IMPLIED BaseEnjoyment CDATA #IMPLIED>


<!ELEMENT Performance (Factor|Trait|Mod)*>
<!ATTLIST Performance Modifier CDATA #IMPLIED>
<!ELEMENT Factor EMPTY>
<!ATTLIST Factor Skill CDATA #IMPLIED Stat CDATA #IMPLIED Weight CDATA #IMPLIED Min CDATA #IMPLIED Max CDATA #IMPLIED>

<!ELEMENT Gains (GainTrait|LoseTrait|Skill|Stat)*>
<!ATTLIST Gains XP CDATA #IMPLIED Skill CDATA #IMPLIED>
<!ELEMENT GainTrait (TraitChangeAmount,Text)>
<!ATTLIST GainTrait Trait CDATA #REQUIRED Event CDATA #IMPLIED Chance CDATA #IMPLIED>
<!ELEMENT LoseTrait (TraitChangeAmount,Text)>
<!ATTLIST LoseTrait Trait CDATA #REQUIRED Event CDATA #IMPLIED Chance CDATA #IMPLIED>
<!ELEMENT Skill (EMPTY)>
<!ATTLIST Skill Name CDATA #REQUIRED Weight CDATA Min CDATA Max CDATA>
<!ELEMENT Stat (EMPTY)>
<!ATTLIST Stat Name CDATA #REQUIRED Weight CDATA Min CDATA Max CDATA>
<!ELEMENT TraitChangeAmount (TraitChangeCondition?)>
<!ATTLIST TraitChangeAmount Value CDATA #REQUIRED Chance CDATA #IMPLIED>
<!ELEMENT TraitChangeCondition EMPTY>
<!ATTLIST TraitChangeCondition Value CDATA #IMPLIED Lower CDATA #IMPLIED Upper CDATA #IMPLIED What CDATA #REQUIRED>

<!ELEMENT Messages (Message|Include)*)>
<!ELEMENT Message ((Text|Group)+)>
<!ATTLIST Message Name CDATA #REQUIRED>
<!ELEMENT Text (#PCDATA)>
<!ATTLIST Text Condition CDATA #IMPLIED Priority CDATA #IMPLIED Chance CDATA #IMPLIED Updates CDATA #IMPLIED>
<!ELEMENT Group ((Text|Group)+)>
<!ATTLIST Group Condition CDATA #IMPLIED Priority CDATA #IMPLIED Chance CDATA #IMPLIED Updates CDATA #IMPLIED>

<!ELEMENT Modifiers (Modifier)*>
<!ELEMENT Modifier (Trait)*>
<!ATTLIST Modifier Name CDATA #REQUIRED>
<!ELEMENT Trait (EMPTY)*>
<!ATTLIST Trait Name CDATA #REQUIRED Value CDATA #REQUIRED>

<!ELEMENT Mod (#PCDATA)>
<!ATTLIST Mod Weight CDATA #IMPLIED>

<!ELEMENT Include (#PCDATA)>

<!-- Only for treatment-type jobs -->
<!ELEMENT Treatment ANY>
<!ATTLIST Treatment Duration CDATA #REQUIRED FightChance CDATA #IMPLIED Title CDATA #IMPLIED>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/FilmHand.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="FHJ" Title="Pornstar">
    <Description>
        She will perform in a hand job scene.
    </Description>

    <Config DefaultImage="Hand">
        <Enjoyment BaseEnjoyment="-5" PrimaryAction="Fucking" SecondaryAction="Performing" />
        <Obedience Difficulty="30" Dignity="55" />
        <Pleasure Amount="10" SkillMin="20" BaseValue="5" Skill="Handjob" />
    </Config>

    <Performance>
        <Factor Stat="Beauty" Weight="1"/>
        <Factor Stat="Charisma" Weight="2"/>
        <Factor Skill="Performance" Weight="2"/>
        <Factor Skill="Handjob" Weight="1"/>

        <Mod>work.pornstar</Mod>
        <Trait Name="Lesbian" Value="-15" />
        <Trait Name="Clumsy" Value="-5" />
        <Trait Name="No Hands" Value="-100" />
    </Performance>

    <Gains XP="15" Skill="3">
        <Skill Name="Performance" Weight="2" Max="75"/>
        <Skill Name="Handjob" Weight="1" Max="50"/>

        <GainTrait Trait="Porn Star" >
            <TraitChangeAmount Value="40" Chance="50">
                <TraitChangeCondition What="JobPerformance" Lower="100" Upper="200" />
            </TraitChangeAmount>
            <Text>She has performed in enough sex scenes that she has become a well known Porn Star.</Text>
        </GainTrait>

        <GainTrait Trait="Idol" >
            <TraitChangeAmount Value="15" Chance="20">
                <TraitChangeCondition What="JobPerformance" Lower="100" Upper="200" />
                <TraitChangeCondition What="Fame" Lower="50" Upper="100" />
            </TraitChangeAmount>
            <Text>Her on-camera handjobs have become legendary, ${name} truly is an Idol.</Text>
        </GainTrait>

        <LoseTrait Trait="Chaste">
            <TraitChangeAmount Value="50" Chance="50" />
            <Text>She has been filmed having sex so often that she is no longer Chaste.</Text>
        </LoseTrait>
    </Gains>

    <Messages>
        <Message Name="work">
            <Text>${name} worked as an actress filming handjob scenes.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to film a handjob scene today.</Text>
        </Message>


        <Message Name="work.perfect">
            <Text>${name} expertly worked his cock and balls. She almost worshipped it!</Text>
            <Text Condition="One Arm|One Hand">
                ${name} may have only one hand, but she sure knows how to use it.
            </Text>
        </Message>

        <Message Name="work.great">
            <Text>${name} loved giving him a great handjob.</Text>
        </Message>

        <Message Name="work.good">
            <Text>${name} enjoyed tickling him a bit while she gave a decent handjob.</Text>
            <Text Condition="Lesbian">
                ${name} is a decent actress, so despite her personal aversion, she managed to make a good handjob scene.
            </Text>
        </Message>

        <Message Name="work.ok">
            <Text>${name} was ok with the handjob today. She almost wants to do other scenes.</Text>
            <Text Condition="Lesbian">
                ${name}'s handjob was ok, considering that she prefers pussy over cock.
            </Text>
        </Message>

        <Message Name="work.bad">
            <Text>${name} sucked doing the handjob, she was like a drone.</Text>
            <Text Condition="Lesbian">
                ${name} performed a very lacklustre handjob. Maybe it is because she herself has no interest in cock.
            </Text>

            <Text Condition="stat:Beauty>80|Great Figure|Hourglass Figure">
                The Director instructed the Camera Mage to focus more on her figure than on the action. But even with
                clever editing, the scene will be bad.
            </Text>
        </Message>

        <Message Name="work.worst">
            <Text>${name} was the worst actress the Director ever saw. She might be better at behind the scenes jobs.</Text>
            <Text Condition="Lesbian">
                With her dislike of $[cock][dick][penises] so clearly written on her face, ${name} really is unsuited for a handjob scene.
            </Text>
            <Text Condition="One Arm|One Hand">
                One-handed ${name}'s attempts at a handjob succeeded in keeping you crew entertained, but will probably
                only make the blooper reel of your next movie.
            </Text>
        </Message>

        <Message Name="post-work-event">
            <Text Condition="Dick-Sucking Lips ^ Performance < 125" Chance="50">
                With those lips of hers, maybe you should have instructed her to to a blowjob scene.
            </Text>
            <Text Condition="Porn Star ^ Performance < 125" Chance="50">
                From a Porn Star as experienced as ${name} you would have expected better results.
            </Text>
            <Text Condition="skill:Handjob > 80 ^ Performance < 125" Chance="50">
                Even though it doesn't really show on film, ${name}'s costar swears that this was one of the best
                handjobs he's ever had.
            </Text>
        </Message>
    </Messages>
</Job>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/ArenaCobbler.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Cblr">
    <Description>
        She will make shoes and leather items.
    </Description>

    <Performance>
        <Factor Skill="Crafting" Weight="3"/>
        <Factor Skill="Service" Weight="1"/>
        <Factor Skill="Magic" Weight="1"/>
        <Factor Stat="Intelligence" Weight="1"/>
    </Performance>

    <Gains XP="10" Skill="3">
        <Skill Name="Crafting" Weight="3"/>
        <Skill Name="Service" Weight="1"/>
        <Skill Name="Magic" Weight="1"/>
    </Gains>

    <Config DefaultImage="Craft" />

    <Messages>
        <Message Name="work">
            <Text>${name} worked making shoes and other leather items at the arena.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to work as a cobbler during the ${shift} shift.</Text>
        </Message>
        <Message Name="repair">
            <Text>"She spent some of her time repairing the Arena's equipment instead of making new stuff.</Text>
        </Message>
        <Message Name="produce">
            <Text>${name} made:</Text>
        </Message>
        <Include>DefaultPerformanceMessages.xml</Include>
    </Messages>
</Job>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/ArenaFightTrain.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="CT">
    <Description>
        She will practice combat.
    </Description>

    <Config DefaultImage="Combat" FightingJob="1" BaseWages="20">
        <Filter>ArenaFight</Filter>
        <Enjoyment PrimaryAction="Fighting" SecondaryAction="Physical"/>
        <Obedience Difficulty="10" Fear="25" />
    </Config>

    <Performance />

    <Messages>
        <Message Name="refuse">
            <Text>${name} refused to work during the ${shift} shift.</Text>
        </Message>
        <Message Name="work">
            <Text>${name} trains for combat.</Text>
        </Message>
    </Messages>
</Job>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/Butcher.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Bchr">
    <Description>
        She will produce food from animals you own.
    </Description>

    <Performance>
        <Factor Skill="AnimalHandling" Weight="2"/>
        <Factor Stat="Strength" Weight="2"/>
        <Factor Skill="Medicine" Weight="1"/>
        <Factor Skill="Cooking" Weight="1"/>
        <Factor Stat="Intelligence" Weight="1"/>

        <!-- good traits -->
        <Trait Name="Quick Learner" Value="5"/>
        <Trait Name="Psychic" Value="10"/>
        <Trait Name="Farmers Daughter" Value="20"/>
        <Trait Name="Country Gal" Value="10"/>

        <!-- bad traits -->
        <Trait Name="Dependent" Value="-50"/> <!-- needs others to do the job -->
        <Trait Name="Clumsy" Value="-20"/> <!-- spills food and breaks things often -->
        <Trait Name="Aggressive" Value="-20"/> <!-- gets mad easy -->
        <Trait Name="Nervous" Value="-30"/> <!-- don't like to be around people -->
        <Trait Name="Meek" Value="-20"/>

        <Trait Name="One Arm" Value="-40"/>
        <Trait Name="One Foot" Value="-20"/>
        <Trait Name="One Hand" Value="-30"/>
        <Trait Name="One Leg" Value="-35"/>
        <Trait Name="No Arms" Value="-125"/>
        <Trait Name="No Feet" Value="-40"/>
        <Trait Name="No Hands" Value="-50"/>
        <Trait Name="No Legs" Value="-75"/>
        <Trait Name="Blind" Value="-30"/>
        <Trait Name="Retarded" Value="-60"/>
        <Trait Name="Smoker" Value="-10"/> <!-- would need smoke breaks -->

        <Trait Name="Alcoholic" Value="-25"/>
        <Trait Name="Fairy Dust Addict" Value="-25"/>
        <Trait Name="Shroud Addict" Value="-25"/>
        <Trait Name="Viras Blood Addict" Value="-25"/>
    </Performance>

    <Gains XP="10" Skill="3">
        <Skill Name="AnimalHandling" Weight="2" />
        <Stat Name="Strength" Weight="2" />
        <Skill Name="Medicine" Weight="1" Max="33" />
        <Skill Name="Cooking" Weight="1" />
        <GainTrait Trait="Chef" Threshold="70" Action="COOKING">
            ${name} has prepared enough food to qualify as a Chef.
        </GainTrait>
    </Gains>

    <Config DefaultImage="Cook" />

    <Messages>
        <Message Name="work">
            <Text>${name} worked as a butcher on the farm.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to work as a butcher during the ${shift} shift.</Text>
        </Message>
        <Message Name="repair">
            <Text>She spent some of her time repairing the Farm's equipment instead of making new stuff.</Text>
        </Message>
        <Message Name="produce">
            <Text>${name} made:</Text>
        </Message>
        <Include>DefaultPerformanceMessages.xml</Include>
    </Messages>
</Job>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/FeedPoor.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Feed">
    <Description>
        She will work in a soup kitchen.
    </Description>

    <Config BaseWages="20">
        <Enjoyment BaseEnjoyment="5" PrimaryAction="Service" SecondaryAction="Social" />
        <Obedience Difficulty="25" Fear="10" Dignity="80"/>
        <Filter>CommunityCentre</Filter>
    </Config>

    <Performance>
        <Factor Stat="Intelligence" Weight="1" />
        <Factor Stat="Charisma" Weight="1" />
        <Factor Skill="Service" Weight="2" />
        <Mod>work.communityservice</Mod>
    </Performance>

    <Gains XP="15" Skill="3">
        <Stat Name="Intelligence" Weight="1" Max="50"/>
        <Stat Name="Charisma" Weight="1" Max="50"/>
        <Skill Name="Service" Weight="1" Max="70"/>

        <GainTrait Trait="Chef" >
            <!-- Just so it doesn't decay -->
            <TraitChangeAmount Value="1" Chance="50" />
        </GainTrait>

        <LoseTrait Trait="Merciless">
            <TraitChangeAmount Value="60" Chance="50">
                <TraitChangeCondition What="JobPerformance" Lower="100" Upper="200"/>
            </TraitChangeAmount>
            <Text>Seeing the poor of the city every day, ${name} could not maintain her Merciless attitude.</Text>
        </LoseTrait>

        <GainTrait Trait="Compassionate">
            <TraitChangeAmount Value="50" Chance="50">
                <TraitChangeCondition What="JobPerformance" Lower="120" Upper="220"/>
            </TraitChangeAmount>
            <Text>Helping so many people has made ${name} quite Compassionate.</Text>
        </GainTrait>

        <LoseTrait Trait="Shy">
            <TraitChangeAmount Value="40" Chance="33">
                <TraitChangeCondition What="Confidence" Lower="10" Upper="40"/>
            </TraitChangeAmount>
            <Text>Interacting with the poor of Crossgate on a regular basis,
                ${name} seems to finally be getting over her Shyness.</Text>
        </LoseTrait>
    </Gains>

    <Messages>
        <Message Name="refuse">
            <Text>${name} refused to work during the ${shift} shift.</Text>
        </Message>
        <Message Name="work">
            <Text>${name} worked feeding the poor.</Text>
        </Message>

        <Message Name="work.perfect">
            She must be perfect at this.
            <Text>
                Today ${name} was managing the kitchen giving orders to other cooks and checking the quality of their work.
            </Text>
            <Text>
                ${name} was helping in the kitchen. Her task was to stir-fry vegetables. One word: Perfection. Food that she prepared was great!
            </Text>
            <Text>
                Being done with the main dish earlier, ${name} decided to bake cookies for desert!
            </Text>
            <Text>
                Excellent dish! Some world class chefs should learn from ${name}!
            </Text>
            <Text>
                ${name} knife skill is impressive. She's cutting precisely and really fast, almost like a machine.
            </Text>
        </Message>
        <Message Name="work.great">
            She's unbelievable at this and is always getting praised by people for her work.
            <Text>
                ${name} is in charge of the cooking for several weeks now.
                You could swear that the population of rodents and small animals in the area went down.
            </Text>
            <Text>
                While preparing for today's cooking, ${name} noticed that one of the crucial ingredients is missing.
                She manage to change the menu and fully use available ingredients.
            </Text>
            <Text>
                She speedily served all in line at the food counter. All the portions handed out were equal.
            </Text>
            <Text>
                Preparing something new she mixed up the proportions from the recipe. The outcome tasted great!
            </Text>
            <Text>
                ${name} was helping in the kitchen. Her task was to prepare the souse for today's meatballs.
                The texture and flavor was top notch.
            </Text>
        </Message>
        <Message Name="work.good">
            She's good at this job and gets praised by people often.
            <Text>While cooking she used everything that was in the kitchen. Nothing was wasted.</Text>
            <Text>While cooking she accidentally sneezed into the pot. Luckily nobody saw that.</Text>
            <Text>"${name} was helping in the kitchen.
                Her task was to carve the meat.
                Smile on her face that appear while doing this, was somehow scary and disturbing.</Text>
            <Text>${name} was doing the dishes. Most of them "survived" and will be used next time.</Text>
            <Text>She spent her shift at the food counter without any trouble.</Text>
        </Message>
        <Message Name="work.ok">
            She made a few mistakes but overall she is okay at this.
            <Text>Her cooking isn't very good. But You probably would risk serving the prepared dish to a dog.</Text>
            <Text>Today she was assign as the cook. Not being able to focus on the task at hand, she overcooked the pasta.</Text>
            <Text>She served all in line at the food counter. Some portions were smaller than others.</Text>
            <Text>${name} was helping in the kitchen. Her task was to make a salad. She manage to do this much.</Text>
            <Text>When walking with a pile of clean dished she slipped and fall. All the plates got broken.</Text>
        </Message>
        <Message Name="work.bad">
            She was nervous and made a few mistakes. She isn't that good at this.
            <Text>Today she was assign as the cook. Meatballs that she prepared could be used as lethal projectiles.</Text>
            <Text>${name} was doing the dishes.
                Let's say it would be a lot quicker to throw them all right away,
                then wait for her to break so many during this simple chore.
            </Text>
            <Text>While cooking she burned two brand new pots!</Text>
            <Text>
                ${name} was helping in the kitchen. Her task was to dice the carrots.
                Surely the carrots were cut, but to called them diced would be an exaggeration.
            </Text>
            <Text>Just wanting to serve the food fast to end her shift. She did a sloppy job at the food counter.</Text>
        </Message>
        <Message Name="work.worst">
            She was nervous and constantly making mistakes. She really isn't very good at this job.
            <Text>While preparing ingredients for the soup she almost cut off her hand!</Text>
            <Text>
                ${name} was helping in the kitchen. Her task was to peel the potatoes.
                The peels were thick and had a lot of the vegetable left on them. What a waste!
            </Text>
            <Text>Today she was assigned as the cook. The thing that she created hardly could be called food.</Text>
            <Text>
                Today she was assigned to work at the food counter.
                While handing out food she served different portions to people in line.
            </Text>
            <Text>Being assigned to the food counter, she put a sign "self serving" and went out.</Text>
        </Message>

        <Message Name="event.sex">
            <Text>Her Lust got the better of her today and she decided to let them eat her pussy! After a few minutes they started fucking her.</Text>
        </Message>
    </Messages>
</Job>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/Whore.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<!-- TODO currently using Dummy values because there are different variations of the job -->
<Job ShortName="DUMMY">
    <Description>
       DUMMY
    </Description>

    <Gains XP="0" Skill="0">
        <GainTrait Trait="Good Kisser">
            <TraitChangeAmount Value="50" Chance="50">
                <TraitChangeCondition What="JobPerformance" Lower="150" Upper="200" />
            </TraitChangeAmount>
            <Text>${name} has had a lot of practice kissing and as such has become a Good Kisser.</Text>
        </GainTrait>

        <GainTrait Trait="Slut" Event="2">
            <TraitChangeAmount Value="40" Chance="33">
                <TraitChangeCondition What="Libido" Lower="50" Upper="80" />
            </TraitChangeAmount>
            <Text>${name} has turned into quite a Slut.</Text>
        </GainTrait>

        <GainTrait Trait="Nymphomaniac">
            <TraitChangeAmount Value="30" Chance="25">
                <TraitChangeCondition What="Libido" Lower="0" Upper="50"/>
            </TraitChangeAmount>
            <TraitChangeAmount Value="100" Chance="5">
                <TraitChangeCondition What="Libido" Lower="80" Upper="90"/>
            </TraitChangeAmount>
            <Text>${name} has been having so much sex that she has become a total Nympho.</Text>
        </GainTrait>

        <LoseTrait Trait="Chaste">
            <TraitChangeAmount Value="80" Chance="50" />
            <Text>She has been having sex for money so often that she is no longer Chaste.</Text>
        </LoseTrait>
    </Gains>
</Job>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/FarmCatacombRancher.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="CRnc" Title="Catacomb Rancher">
    <Description>
        She will tend to strange beasts.
    </Description>

    <Config DefaultImage="Herd" BaseWages="40" FightingJob="1">
        <Enjoyment BaseEnjoyment="-2" PrimaryAction="Farming" SecondaryAction="Fighting"/>
        <Obedience Difficulty="30" Fear="33" Dignity="60"/>
        <WageFunction>
            <Point Performance="245" Wages="155" />
            <Point Performance="185" Wages="95" />
            <Point Performance="145" Wages="55" />
            <Point Performance="100" Wages="15" />
            <Point Performance="70" Wages="-5" />
            <Point Performance="0" Wages="-15" />
        </WageFunction>
    </Config>

    <Performance>
        <Factor Skill="AnimalHandling" Weight="3"/>
        <Factor Stat="Confidence" Weight="1"/>
        <Factor Stat="Strength" Weight="1"/>
        <Factor Stat="Constitution" Weight="1"/>

        <!-- good traits -->
        <Trait Name="Quick Learner" Value="5"/>
        <Trait Name="Psychic" Value="10"/>
        <Trait Name="Farmers Daughter" Value="30"/>
        <Trait Name="Country Gal" Value="10"/>

        <!-- bad traits -->
        <Trait Name="Dependent" Value="-50"/> <!-- needs others to do the job -->
        <Trait Name="Clumsy" Value="-20"/> <!-- spills food and breaks things often -->
        <Trait Name="Aggressive" Value="-20"/> <!-- gets mad easy -->
        <Trait Name="Nervous" Value="-30"/> <!-- don't like to be around people -->
        <Trait Name="Meek" Value="-20"/>

        <Trait Name="One Arm" Value="-40"/>
        <Trait Name="One Foot" Value="-40"/>
        <Trait Name="One Hand" Value="-30"/>
        <Trait Name="One Leg" Value="-60"/>
        <Trait Name="No Arms" Value="-125"/>
        <Trait Name="No Feet" Value="-60"/>
        <Trait Name="No Hands" Value="-50"/>
        <Trait Name="No Legs" Value="-150"/>
        <Trait Name="Blind" Value="-30"/>
        <Trait Name="Deaf" Value="-15"/>
        <Trait Name="Retarded" Value="-60"/>
        <Trait Name="Smoker" Value="-10"/> <!-- would need smoke breaks -->

        <Trait Name="Alcoholic" Value="-25"/>
        <Trait Name="Fairy Dust Addict" Value="-25"/>
        <Trait Name="Shroud Addict" Value="-25"/>
        <Trait Name="Viras Blood Addict" Value="-25"/>
    </Performance>

    <Gains XP="15" Skill="3">
        <Skill Name="AnimalHandling" Weight="3" />
        <Stat Name="Confidence" Weight="1" />
        <Stat Name="Strength" Weight="1" />
        <Stat Name="Constitution" Weight="1" />

        <LoseTrait Trait="Elegant">
            <TraitChangeAmount Value="100" Chance="50" />
            <Text>Working with dirty, smelly beasts has damaged ${name}'s hair,
                skin and nails making her less Elegant.</Text>
        </LoseTrait>
    </Gains>

    <Messages>
        <Message Name="work">
            <Text>${name} worked as a catacomb rancher on the farm.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to work during the ${shift} shift.</Text>
        </Message>

        <Message Name="work.perfect">
            <Text>She must be perfect at this.</Text>
        </Message>
        <Message Name="work.great">
            <Text>She's unbelievable at this and is always getting praised by people for her work.</Text>
        </Message>
        <Message Name="work.good">
            <Text>She's good at this job and gets praised by people often.</Text>
        </Message>
        <Message Name="work.ok">
            <Text>She made a few mistakes but overall she is okay at this.</Text>
        </Message>
        <Message Name="work.bad">
            <Text>She was nervous and made a few mistakes. She isn't that good at this.</Text>
        </Message>
        <Message Name="work.worst">
            <Text>She was nervous and constantly making mistakes. She really isn't very good at this job.</Text>
        </Message>
    </Messages>
</Job>
