=== h1262216/crazys-wm-mod/Resources/Data/Jobs/job.dtd
<!ELEMENT Job (Description, Performance, Modifiers?, Gains, Config?, Treatment?, Messages?)>
<!ATTLIST Job ShortName CDATA #REQUIRED>

<!ELEMENT Description (#PCDATA)>
<!ELEMENT Config (Filter, Enjoyment)>
<!ATTLIST Config Shift (both|day-only|night-only|full) FreeOnly (0|1) #IMPLIED DefaultImage CDATA #IMPLIED
        Phase (prepare|produce|main|late) #IMPLIED FightingJob (0|1) #IMPLIED BaseWages CDATA #IMPLIED>
<!ELEMENT Filter (#PCDATA)>
<!ELEMENT Enjoyment EMPTY>
<!ATTLIST Enjoyment PrimaryAction CDATA #IMPLIED SecondaryAction CDATA #IMPLIED BaseEnjoyment CDATA #IMPLIED>


<!ELEMENT Performance (Factor|Trait|Mod)*>
<!ATTLIST Performance Modifier CDATA #IMPLIED>
<!ELEMENT Factor EMPTY>
<!ATTLIST Factor Skill CDATA #IMPLIED Stat CDATA #IMPLIED Weight CDATA #IMPLIED Min CDATA #IMPLIED Max CDATA #IMPLIED>

<!ELEMENT Gains (GainTrait|LoseTrait|Skill|Stat)*>
<!ATTLIST Gains XP CDATA #IMPLIED Skill CDATA #IMPLIED>
<!ELEMENT GainTrait (TraitChangeAmount,Text)>
<!ATTLIST GainTrait Trait CDATA #REQUIRED Event CDATA #IMPLIED Chance CDATA #IMPLIED>
<!ELEMENT LoseTrait (TraitChangeAmount,Text)>
<!ATTLIST LoseTrait Trait CDATA #REQUIRED Event CDATA #IMPLIED Chance CDATA #IMPLIED>
<!ELEMENT Skill (EMPTY)>
<!ATTLIST Skill Name CDATA #REQUIRED Weight CDATA Min CDATA Max CDATA>
<!ELEMENT Stat (EMPTY)>
<!ATTLIST Stat Name CDATA #REQUIRED Weight CDATA Min CDATA Max CDATA>
<!ELEMENT TraitChangeAmount (TraitChangeCondition?)>
<!ATTLIST TraitChangeAmount Value CDATA #REQUIRED Chance CDATA #IMPLIED>
<!ELEMENT TraitChangeCondition EMPTY>
<!ATTLIST TraitChangeCondition Value CDATA #IMPLIED Lower CDATA #IMPLIED Upper CDATA #IMPLIED What CDATA #REQUIRED>

<!ELEMENT Messages (Message|Include)*)>
<!ELEMENT Message ((Text|Group)+)>
<!ATTLIST Message Name CDATA #REQUIRED>
<!ELEMENT Text (#PCDATA)>
<!ATTLIST Text Condition CDATA #IMPLIED Priority CDATA #IMPLIED Chance CDATA #IMPLIED Updates CDATA #IMPLIED>
<!ELEMENT Group ((Text|Group)+)>
<!ATTLIST Group Condition CDATA #IMPLIED Priority CDATA #IMPLIED Chance CDATA #IMPLIED Updates CDATA #IMPLIED>

<!ELEMENT Modifiers (Modifier)*>
<!ELEMENT Modifier (Trait)*>
<!ATTLIST Modifier Name CDATA #REQUIRED>
<!ELEMENT Trait (EMPTY)*>
<!ATTLIST Trait Name CDATA #REQUIRED Value CDATA #REQUIRED>

<!ELEMENT Mod (#PCDATA)>
<!ATTLIST Mod Weight CDATA #IMPLIED>

<!ELEMENT Include (#PCDATA)>

<!-- Only for treatment-type jobs -->
<!ELEMENT Treatment ANY>
<!ATTLIST Treatment Duration CDATA #REQUIRED FightChance CDATA #IMPLIED Title CDATA #IMPLIED>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/ArenaBlacksmith.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Bksm">
    <Description>
        She will make weapons and armor.
    </Description>

    <Performance>
        <Factor Skill="Crafting" Weight="2"/>
        <Factor Stat="Strength" Weight="2"/>
        <Factor Skill="Combat" Weight="1"/>
        <Factor Skill="Magic" Weight="1"/>
        <Factor Stat="Intelligence" Weight="1"/>
        <Factor Stat="Constitution" Weight="1"/>

        <Trait Name="Clumsy" Value="-10" />
    </Performance>

    <Config DefaultImage="Craft" />

    <Gains XP="10" Skill="3">
        <Skill Name="Crafting" Weight="2" />
        <Stat Name="Strength" Weight="2" />
        <Stat Name="Constitution" Weight="2" />
        <Skill Name="Combat" Weight="1" />
        <Skill Name="Magic" Weight="1" />

        <GainTrait Trait="Tough">
            <TraitChangeAmount Value="50" Chance="50">
                <TraitChangeCondition What="Strength" Lower="25" Upper="50" />
            </TraitChangeAmount>
            <Text>Working in the heat of the forge has made ${name} rather Tough.</Text>
        </GainTrait>

        <GainTrait Trait="Manly">
            <TraitChangeAmount Value="33" Chance="50">
                <TraitChangeCondition What="Strength" Lower="60" Upper="100" />
            </TraitChangeAmount>
            <Text>The grueling work in the forge has made ${name} appear rather Manly.</Text>
        </GainTrait>

        <LoseTrait Trait="Fragile">
            <TraitChangeAmount Value="100" Chance="50" />
            <Text>Working in the heat of the forge has made ${name} lose her Fragility.</Text>
        </LoseTrait>
    </Gains>

    <Messages>
        <Message Name="work">
            <Text>${name} worked as a blacksmith at the arena.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to work in the smithy during the ${shift} shift.</Text>
        </Message>
        <Message Name="repair">
            <Text>She spent some of her time repairing the Arena's equipment instead of making new stuff.</Text>
        </Message>
        <Message Name="produce">
            <Text>${name} made:</Text>
        </Message>
        <Include>DefaultPerformanceMessages.xml</Include>
    </Messages>
</Job>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/Fluffer.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Fluf" Title="Fluffer">
    <Description>
        She will keep the porn stars aroused.
    </Description>

    <Config DefaultImage="Blowjob" BaseWages="50" Phase="Produce">
        <Enjoyment BaseEnjoyment="-10" PrimaryAction="Fucking" SecondaryAction="Service" />
        <Filter>StudioCrew</Filter>
        <Obedience Dignity="50" Difficulty="20" Fear="5" />
    </Config>

    <Performance>
        <Factor Stat="Beauty" Weight="1"/>
        <Factor Skill="OralSex" Weight="1"/>
        <Factor Skill="Service" Weight="1"/>
    </Performance>

    <Gains XP="15" Skill="1">
        <Skill Name="OralSex" Weight="1" />
        <Skill Name="Service" Weight="1" />

        <GainTrait Trait="Slut" Event="2">
            <TraitChangeAmount Value="30" Chance="33">
                <TraitChangeCondition What="Libido" Lower="50" Upper="80" />
            </TraitChangeAmount>
            <Text>${name} has turned into quite a Slut.</Text>
        </GainTrait>

        <GainTrait Trait="Cum Addict" Event="2">
            <TraitChangeAmount Value="25" Chance="20">
                <TraitChangeCondition What="Libido" Lower="50" Upper="80" />
            </TraitChangeAmount>
            <Text>${name} has become addicted to Cum.</Text>
        </GainTrait>
    </Gains>

    <Messages>
        <Message Name="no-crew">
            <Text>There was no crew to film the scene, so ${name} took the day off.</Text>
        </Message>
        <Message Name="no-actress">
            <Text>There were no actresses to film, so ${name} took the day off.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to work as a fluffer today.</Text>
        </Message>
        <Message Name="work">
            <Text>${name} worked as a fluffer.</Text>
        </Message>
        <Message Name="work.perfect">
            <Text>
                She was so skillful in keeping the actors aroused that your camera mage decided to film some of her work
                too. This will be a great after-credits shot.
            </Text>
        </Message>
        <Message Name="work.great">
            <Text>
                Who needs blue pills and aphrodisiacs when you have ${name}. She is great at keeping the actors ready to
                work.
            </Text>
        </Message>
        <Message Name="work.good">
            <Text>
                She did a good job of keeping the actors aroused.
            </Text>
        </Message>
        <Message Name="work.ok">
            <Text>
                She does a decent job of keeping the actors ready.
            </Text>
        </Message>
        <Message Name="work.bad">
            <Text>
                She is supposed to keep the actors aroused, but her attempts left them amused at best.
            </Text>
        </Message>
        <Message Name="work.worst">
            <Text>
                Her performance on set has earned her the nickname "The Limper". This has nothing to do with the way she
                walks.
            </Text>
        </Message>
    </Messages>
</Job>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/FarmMarketer.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Mrkt">
    <Description>
        She will buy and sell things.
    </Description>

    <Config BaseWages="20">
        <Enjoyment PrimaryAction="Social"/>
    </Config>

    <Performance>
        <Factor Stat="Charisma" Weight="3"/>
        <Factor Stat="Confidence" Weight="3"/>
        <Factor Stat="Intelligence" Weight="2"/>
        <Factor Stat="Fame" Weight="2"/>
        <Factor Skill="Farming" Weight="2"/>

        <!-- good traits -->
        <Trait Name="Charismatic" Value="15"/>
        <Trait Name="Sexy Air" Value="5"/>
        <Trait Name="Cool Person" Value="10"/>  <!-- people love to be around her -->
        <Trait Name="Cute" Value="5"/>
        <Trait Name="Charming" Value="15"/>  <!-- people like charming people -->
        <Trait Name="Quick Learner" Value="5"/>
        <Trait Name="Psychic" Value="10"/>

        <!-- bad traits -->
        <Trait Name="Dependent" Value="-50"/> <!-- needs others to do the job -->
        <Trait Name="Clumsy" Value="-20"/> <!-- spills food and breaks things often -->
        <Trait Name="Aggressive" Value="-20"/> <!-- gets mad easy -->
        <Trait Name="Nervous" Value="-30"/> <!-- don't like to be around people -->
        <Trait Name="Meek" Value="-20"/>
    </Performance>

    <Gains XP="10" Skill="3">
        <Stat Name="Charisma" Weight="1" />
        <Stat Name="Confidence" Weight="1" />
        <Stat Name="Fame" Weight="1" />

        <GainTrait Trait="Charismatic">
            <TraitChangeAmount Value="40" Chance="50">
                <TraitChangeCondition What="Confidence" Lower="20" Upper="50"/>
                <TraitChangeCondition What="Performance" Lower="20" Upper="50"/>
                <TraitChangeCondition What="Charisma" Lower="10" Upper="40"/>
            </TraitChangeAmount>
            <Text>${name} has been selling long enough that she has learned to be more Charismatic.</Text>
        </GainTrait>

        <GainTrait Trait="Psychic">
            <TraitChangeAmount Value="100" Chance="10">
                <TraitChangeCondition What="JobPerformance" Lower="180" Upper="220"/>
            </TraitChangeAmount>
            <Text>${name} has learned to size up the buyers so well that you'd almost think she was Psychic.</Text>
        </GainTrait>

        <LoseTrait Trait="Nervous">
            <TraitChangeAmount Value="40" Chance="33">
                <TraitChangeCondition What="Confidence" Lower="10" Upper="40"/>
            </TraitChangeAmount>
            <Text>${name} seems to finally be getting over her Nervousness.</Text>
        </LoseTrait>

        <LoseTrait Trait="Shy">
            <TraitChangeAmount Value="40" Chance="50">
                <TraitChangeCondition What="Confidence" Lower="0" Upper="33"/>
            </TraitChangeAmount>
            <Text>${name} has been selling for so long now that her confidence is super high, and she is no longer Shy.</Text>
        </LoseTrait>

        <LoseTrait Trait="Meek">
            <TraitChangeAmount Value="60" Chance="50">
                <TraitChangeCondition What="Confidence" Lower="0" Upper="33"/>
            </TraitChangeAmount>
            <Text>${name}'s having to work with customers every day has forced her to get over her Meekness.</Text>
        </LoseTrait>
    </Gains>

    <Messages>
        <Message Name="work">
            <Text>${name} worked as a marketer on the farm.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to work during the ${shift} shift.</Text>
        </Message>

        <Message Name="work.perfect">
            <Text>She must be perfect at this.</Text>
        </Message>
        <Message Name="work.great">
            <Text>She's unbelievable at this and is always getting praised by people for her work.</Text>
        </Message>
        <Message Name="work.good">
            <Text>She's good at this job and gets praised by people often.</Text>
        </Message>
        <Message Name="work.ok">
            <Text>She made a few mistakes but overall she is okay at this.</Text>
        </Message>
        <Message Name="work.bad">
            <Text>She was nervous and made a few mistakes. She isn't that good at this.</Text>
        </Message>
        <Message Name="work.worst">
            <Text>She was nervous and constantly making mistakes. She really isn't very good at this job.</Text>
        </Message>
    </Messages>
</Job>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/Recruiter.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Rcrt" Title="Recruiter">
    <Description>
        She will go out and try and recruit girls for you.
    </Description>

    <Config Shift="full" BaseWages="100">
        <Enjoyment PrimaryAction="Social" />
        <Obedience Difficulty="15" Fear="5" Dignity="90" />
    </Config>

    <Requirements FreeOnly="1" />

    <Performance>
        <Factor Stat="PCLove" Weight="1" />
        <Factor Stat="Charisma" Weight="1" />
    </Performance>

    <Gains XP="15" Skill="3">
        <Skill Name="Service" Weight="1"/>
        <Skill Name="Lesbian" Weight="1"/>
        <Stat Name="Charisma" Weight="1" />
        <Stat Name="Intelligence" Weight="1" />

        <GainTrait Trait="Charismatic">
            <TraitChangeAmount Value="40" Chance="50">
                <TraitChangeCondition What="Confidence" Lower="20" Upper="50"/>
                <TraitChangeCondition What="Performance" Lower="20" Upper="50"/>
                <TraitChangeCondition What="Charisma" Lower="10" Upper="40"/>
            </TraitChangeAmount>
            <Text>Dealing with people all day has made ${name} more Charismatic.</Text>
        </GainTrait>

        <GainTrait Trait="Charismatic">
            <TraitChangeAmount Value="50" Chance="10">
                <TraitChangeCondition What="JobPerformance" Lower="150" Upper="200"/>
            </TraitChangeAmount>
            <Text> ${name} has been doing this for so long it's as if she can read minds now.</Text>
        </GainTrait>

        <LoseTrait Trait="Nervous">
            <TraitChangeAmount Value="60" Chance="50">
                <TraitChangeCondition What="Confidence" Lower="10" Upper="40"/>
            </TraitChangeAmount>
            <Text>${name} seems to finally be getting over her Nervousness.</Text>
        </LoseTrait>
    </Gains>

    <Messages>
        <Message Name="work">
            <Text>${name} worked trying to recruit girls for you.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to work during the ${shift} shift.</Text>
        </Message>

        <Message Name="work.perfect">
            <Text>She must be the perfect recruiter."</Text>
        </Message>
        <Message Name="work.great">
            <Text>She's unbelievable at this.</Text>
        </Message>
        <Message Name="work.good">
            <Text>"She's good at this job.</Text>
        </Message>
        <Message Name="work.ok">
            <Text>She made a few mistakes but overall she is okay at this.</Text>
        </Message>
        <Message Name="work.bad">
            <Text>She was nervous and made a few mistakes. She isn't that good at this.</Text>
        </Message>
        <Message Name="work.worst">
            <Text>She was nervous and constantly making mistakes. She really isn't very good at this job.</Text>
        </Message>

        <Message Name="shift.good">
            <Text>She had a pleasant time working.</Text>
        </Message>
        <Message Name="shift.bad">
            <Text>Some of the people abused her during the shift.</Text>
        </Message>
        <Message Name="shift.neutral">
            <Text>Otherwise, the shift passed uneventfully.</Text>
        </Message>
    </Messages>
</Job>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/CrystalPurifier.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="CP" Title="Crystal Purifier">
    <Description>
        She will clean up the filmed scenes. One Purifier can process at most 3 scenes per week.
    </Description>

    <Config DefaultImage="CrystalPurifier" BaseWages="50">
        <Enjoyment BaseEnjoyment="0" PrimaryAction="Crafting" SecondaryAction="Mental" />
        <Obedience Difficulty="15" Fear="0" Dignity="85" />
        <Filter>StudioCrew</Filter>
    </Config>

    <Performance>
        <Factor Stat="Confidence" Weight="1"/>
        <Factor Stat="Refinement" Weight="1"/>
        <Factor Skill="Magic" Weight="1"/>
        <Factor Skill="Crafting" Weight="2"/>

        <Trait Name="Clumsy" Value="-50" />
    </Performance>

    <Gains XP="10" Skill="2">
        <Skill Name="Magic" Weight="1" />
        <Skill Name="Crafting" Weight="2" />
        <Stat Name="Confidence" Weight="1" />

        <GainTrait Trait="Director" >
            <!-- Really only preserving any progress -->
            <TraitChangeAmount Value="1" Chance="50" />
        </GainTrait>

        <LoseTrait Trait="Clumsy">
            <TraitChangeAmount Value="100" Chance="25" />
            <Text>It took her ruining many video crystals, and just as many reprimands,
                but ${name} has finally stopped being so Clumsy.</Text>
        </LoseTrait>
    </Gains>

    <Messages>
        <Message Name="no-crew">
            <Text>There was no crew to film the scene, so ${name} took the day off.</Text>
        </Message>
        <Message Name="no-actress">
            <Text>There were no actresses to film, so ${name} took the day off.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to work as a crystal purifier today.</Text>
        </Message>
        <Message Name="work">
            <Text>${name} was assigned to work as a Crystal Purifier.</Text>
        </Message>
        <Message Name="work.perfect">
            <Text>
                Her skill with movie crystals, together with her deep understanding of colour and contrast allowed
                her to transform the scene into a masterpiece. Truly an outstanding work in post-production.
            </Text>
        </Message>
        <Message Name="work.great">
            <Text>
                She preserves the recordings with great skill, and is able to perform some touch-ups that make the
                scenes look even better.
            </Text>
        </Message>
        <Message Name="work.good">
            <Text>
                She knows how to preserve the recording, and has the skill to edit them further in post-production.
                What ${name} is lacking is the experience on where to edit and how to touch up things in a more subtle
                way.
            </Text>
        </Message>
        <Message Name="work.ok">
            <Text>
                She managed to preserve the recording more or less in the same state as the original film.
            </Text>
        </Message>
        <Message Name="work.bad">
            <Text>
                She managed to preserve the recordings in a storage crystal, though the image is somewhat distorted
                in places.
            </Text>
        </Message>
        <Message Name="work.worst">
            <Text>
                Seeing the cracked movie crystal, you decide that ${name} probably should never again be left
                unsupervised with the footage. It is a wonder that there is still something left of the scene.
            </Text>
        </Message>
    </Messages>
</Job>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/FilmOral.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="FOrl">
    <Description>
        She will perform in an oral sex scene.
    </Description>
    <Performance>
        <Factor Stat="Charisma" Weight="2"/>
        <Factor Stat="Beauty" Weight="1"/>
        <Factor Skill="OralSex" Weight="1"/>
        <Factor Skill="Performance" Weight="2"/>

        <Mod>work.pornstar</Mod>

        <!-- Good -->
        <Trait Name="Deep Throat" Value="60"/> <!-- better ability -->
        <Trait Name="No Gag Reflex" Value="40"/>
        <Trait Name="Good Kisser" Value="20"/>
        <Trait Name="Nimble Tongue" Value="20"/>
        <Trait Name="Pierced Tongue" Value="25"/>
        <Trait Name="Dick-Sucking Lips" Value="35"/>
        <Trait Name="Exotic" Value="5"/>
        <Trait Name="Whore" Value="20"/>   <!-- Knows how to work it -->
        <Trait Name="Porn Star" Value="30"/>   <!-- Knows how to work it on film -->
        <Trait Name="No Teeth" Value="15"/>    <!-- no chance of 'accident' -->
        <Trait Name="Missing Teeth" Value="15"/>
        <Trait Name="Nymphomaniac" Value="25"/>    <!-- had lots of practice -->
        <Trait Name="Slut" Value="15"/>    <!-- had practice -->
        <Trait Name="Cum Addict" Value="30"/>  <!-- eager to please -->
        <Trait Name="Mind Fucked" Value="25"/> <!-- eager to please -->
        <Trait Name="Sexy Air" Value="10"/>
        <Trait Name="Open Minded" Value="10"/>
        <Trait Name="Natural Pheromones" Value="5"/>


        <!-- Bad -->
        <Trait Name="Strong Gag Reflex" Value="-40"/>
        <Trait Name="Gag Reflex" Value="-20"/>
        <Trait Name="Clumsy" Value="-25"/>
    </Performance>

    <Gains XP="15" Skill="3">
        <Skill Name="Performance" Weight="2" Max="75"/>
        <Skill Name="OralSex" Weight="1" Max="50"/>

        <GainTrait Trait="Porn Star" >
            <TraitChangeAmount Value="40" Chance="50">
                <TraitChangeCondition What="JobPerformance" Lower="100" Upper="200" />
            </TraitChangeAmount>
            <Text> She has performed in enough sex scenes that she has become a well known Porn Star.</Text>
        </GainTrait>

        <GainTrait Trait="Cum Addict" Event="2">
            <TraitChangeAmount Value="10" Chance="33">
                <TraitChangeCondition What="Libido" Lower="50" Upper="80" />
            </TraitChangeAmount>
            <Text>${name} has become addicted to Cum.</Text>
        </GainTrait>

        <LoseTrait Trait="Chaste">
            <TraitChangeAmount Value="80" Chance="50" />
            <Text>${name} no longer is Chaste after having been showered in cum.</Text>
        </LoseTrait>
    </Gains>

    <Config PrimaryAction="PORNSTAR" SecondaryAction="SEX">
        <LustInfluence Amount="15" SkillMin="25" BaseValue="10" Skill="OralSex" />
    </Config>

    <Messages>
        <Message Name="work">
            <Text>${name} worked as an actress filming oral scenes.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to give head on film today.</Text>
        </Message>
        <Message Name="work.perfect">
            <Text>
            The lucky guy came uncontrollably, damn near passing out in pleasure as ${name} expertly sucked him dry.
            She savoured the cum in her mouth, rolling it around her lips and tongue before finally swallowing it down.
            </Text>
        </Message>
        <Message Name="work.great">
            ${name} sucked off her man like a pro - not once breaking eye-contact - and was rewarded with
            <Text Condition="Cum Addict" Priority="1">
                a mouthful of semen. She kept her lips clamped to his cock to the last,
                thirstily swallowing down every drop of hot cum.
            </Text>
            <Text>
                a mouthful of semen. She kept her lips clamped to his cock to the last,
                thirstily swallowing down every drop of hot cum.
            </Text>
            <Text>
                an explosion of cum in her face. As she licked his penis clean,
                she rubbed cum around her skin and licked it off her fingers.
            </Text>
        </Message>
        <Message Name="work.good">
            <Text>${name} gave a fairly pleasant blowjob, and ended up glazed in hot cum.</Text>
        </Message>
        <Message Name="work.ok">
            <Text>${name} gave a passable blowjob, but in the end the actor had to finish himself off, splatting cum on her face.</Text>
        </Message>
        <Message Name="work.bad">
            <Text>
                It was a pretty awkward and uncomfortable scene,
                with the actor not getting any kind of pleasure from her clumsy, toothy attempts.
                In the end he gave up and simply wanked in her face, but even then she dodged at the last moment,
                ruining that scene too.
            </Text>
        </Message>
        <Message Name="work.worst">
            <Text>
                After the fourth time she 'snagged' the actor on her tooth, he cursed and stormed off set.
                Your goons saved the day by pinning her down wanking on her face one-by-one.
                Overall it's a terrible scene.
            </Text>
        </Message>
    </Messages>
</Job>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/CustService.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="CS" Title="Customer Service">
    <Description>
        She will look after customer needs.
    </Description>

    <Config BaseWages="50">
        <Enjoyment PrimaryAction="Social" SecondaryAction="Service"/>
        <Obedience Difficulty="25" Fear="5" Dignity="80" />
    </Config>

    <Performance>
        <Factor Stat="Beauty" Weight="2"/>
        <Factor Stat="Confidence" Weight="2"/>
        <Factor Stat="Spirit" Weight="2"/>
        <Factor Skill="Performance" Weight="2"/>

        <Factor Skill="Service" Weight="4"/>
        <Factor Stat="Charisma" Weight="4"/>

        <Mod>work.customerservice</Mod>
    </Performance>

    <Gains XP="10" Skill="3">
        <Skill Name="Performance" Weight="1" Max="50"/>
        <Stat Name="Spirit" Weight="1" Max="50"/>
        <Skill Name="Service" Weight="1" Max="50"/>
        <Stat Name="Confidence" Weight="1" Max="50"/>

        <GainTrait Trait="Charismatic">
            <TraitChangeAmount Value="40" Chance="50">
                <TraitChangeCondition What="Confidence" Lower="20" Upper="50"/>
                <TraitChangeCondition What="Performance" Lower="20" Upper="50"/>
                <TraitChangeCondition What="JobPerformance" Lower="100" Upper="200"/>
            </TraitChangeAmount>
            <Text>Helping customers on a daily basis has made ${name} more Charismatic.</Text>
        </GainTrait>

        <LoseTrait Trait="Nervous">
            <TraitChangeAmount Value="60" Chance="50">
                <TraitChangeCondition What="Confidence" Lower="10" Upper="40"/>
            </TraitChangeAmount>
            <Text>${name} seems to finally be getting over her shyness. She's not always so Nervous anymore.</Text>
        </LoseTrait>
    </Gains>

    <Messages>
        <Message Name="work">
            <Text>${name} worked as Customer Service.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to provide Customer Service in your brothel to${shift}.</Text>
        </Message>
    </Messages>
</Job>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/Security.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="Sec">
    <Description>
        She will patrol the building, stopping mis-deeds.
    </Description>

    <Config DefaultImage="Security" BaseWages="70">
        <Enjoyment PrimaryAction="Fighting"/>
    </Config>

    <Gains XP="15" Skill="3">
        <Skill Name="Combat" Weight="1"/>
        <Skill Name="Magic" Weight="1"/>
        <Stat Name="Agility" Weight="1" />

        <GainTrait Trait="Tough">
            <TraitChangeAmount Value="80" Chance="50">
                <TraitChangeCondition What="Constitution" Lower="33" Upper="50" />
                <TraitChangeCondition What="JobPerformance" Lower="100" Upper="200" />
            </TraitChangeAmount>
            <Text>She has become pretty Tough from all the fights she's been in.</Text>
        </GainTrait>

        <GainTrait Trait="Aggressive" Event="2">
            <TraitChangeAmount Value="20" Chance="25">
                <TraitChangeCondition What="Spirit" Value="50"/>
            </TraitChangeAmount>
            <TraitChangeAmount Value="200" Chance="10" />
            <Text>She is getting rather Aggressive from her enjoyment of combat.</Text>
        </GainTrait>

        <LoseTrait Trait="Meek">
            <TraitChangeAmount Value="100" Chance="50">
                <TraitChangeCondition What="JobPerformance" Lower="50" Upper="200" />
            </TraitChangeAmount>
            <Text>Having to use her authority in the City Guard, ${name} has become less Meek.</Text>
        </LoseTrait>

        <GainTrait Trait="Audacity">
            <TraitChangeAmount Value="50" Chance="25">
                <TraitChangeCondition What="Spirit" Lower="50" Upper="100" />
            </TraitChangeAmount>
            <Text>Being a security guard, ${name} started to get used to abusing her authority. (+Audacity)</Text>
        </GainTrait>
    </Gains>

    <Messages>
        <Message Name="refuse">
            <Text>${name} refused to work security in your brothel to${shift}</Text>
        </Message>
        <Message Name="work">
            <Text>${name} worked Security in the brothel.</Text>
        </Message>
    </Messages>
</Job>
