=== h1262216/crazys-wm-mod/Resources/Data/Jobs/job.dtd
<!ELEMENT Job (Description, Performance, Modifiers?, Gains, Config?, Treatment?, Messages?)>
<!ATTLIST Job ShortName CDATA #REQUIRED>

<!ELEMENT Description (#PCDATA)>
<!ELEMENT Config (Filter, Enjoyment)>
<!ATTLIST Config Shift (both|day-only|night-only|full) FreeOnly (0|1) #IMPLIED DefaultImage CDATA #IMPLIED
        Phase (prepare|produce|main|late) #IMPLIED FightingJob (0|1) #IMPLIED BaseWages CDATA #IMPLIED>
<!ELEMENT Filter (#PCDATA)>
<!ELEMENT Enjoyment EMPTY>
<!ATTLIST Enjoyment PrimaryAction CDATA #IMPLIED SecondaryAction CDATA #IMPLIED BaseEnjoyment CDATA #IMPLIED>


<!ELEMENT Performance (Factor|Trait|Mod)*>
<!ATTLIST Performance Modifier CDATA #IMPLIED>
<!ELEMENT Factor EMPTY>
<!ATTLIST Factor Skill CDATA #IMPLIED Stat CDATA #IMPLIED Weight CDATA #IMPLIED Min CDATA #IMPLIED Max CDATA #IMPLIED>

<!ELEMENT Gains (GainTrait|LoseTrait|Skill|Stat)*>
<!ATTLIST Gains XP CDATA #IMPLIED Skill CDATA #IMPLIED>
<!ELEMENT GainTrait (TraitChangeAmount,Text)>
<!ATTLIST GainTrait Trait CDATA #REQUIRED Event CDATA #IMPLIED Chance CDATA #IMPLIED>
<!ELEMENT LoseTrait (TraitChangeAmount,Text)>
<!ATTLIST LoseTrait Trait CDATA #REQUIRED Event CDATA #IMPLIED Chance CDATA #IMPLIED>
<!ELEMENT Skill (EMPTY)>
<!ATTLIST Skill Name CDATA #REQUIRED Weight CDATA Min CDATA Max CDATA>
<!ELEMENT Stat (EMPTY)>
<!ATTLIST Stat Name CDATA #REQUIRED Weight CDATA Min CDATA Max CDATA>
<!ELEMENT TraitChangeAmount (TraitChangeCondition?)>
<!ATTLIST TraitChangeAmount Value CDATA #REQUIRED Chance CDATA #IMPLIED>
<!ELEMENT TraitChangeCondition EMPTY>
<!ATTLIST TraitChangeCondition Value CDATA #IMPLIED Lower CDATA #IMPLIED Upper CDATA #IMPLIED What CDATA #REQUIRED>

<!ELEMENT Messages (Message|Include)*)>
<!ELEMENT Message ((Text|Group)+)>
<!ATTLIST Message Name CDATA #REQUIRED>
<!ELEMENT Text (#PCDATA)>
<!ATTLIST Text Condition CDATA #IMPLIED Priority CDATA #IMPLIED Chance CDATA #IMPLIED Updates CDATA #IMPLIED>
<!ELEMENT Group ((Text|Group)+)>
<!ATTLIST Group Condition CDATA #IMPLIED Priority CDATA #IMPLIED Chance CDATA #IMPLIED Updates CDATA #IMPLIED>

<!ELEMENT Modifiers (Modifier)*>
<!ELEMENT Modifier (Trait)*>
<!ATTLIST Modifier Name CDATA #REQUIRED>
<!ELEMENT Trait (EMPTY)*>
<!ATTLIST Trait Name CDATA #REQUIRED Value CDATA #REQUIRED>

<!ELEMENT Mod (#PCDATA)>
<!ATTLIST Mod Weight CDATA #IMPLIED>

<!ELEMENT Include (#PCDATA)>

<!-- Only for treatment-type jobs -->
<!ELEMENT Treatment ANY>
<!ATTLIST Treatment Duration CDATA #REQUIRED FightChance CDATA #IMPLIED Title CDATA #IMPLIED>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/FilmAction.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="FAct">
    <Description>
        She will be the scantily clad heroine in fighting/magical action scenes.
    </Description>

    <Config DefaultImage="Combat">
        <Enjoyment BaseEnjoyment="5" PrimaryAction="Performing" SecondaryAction="Fighting" />
        <Obedience Difficulty="20" Fear="5" Dignity="85"/>
    </Config>

    <Performance>
        <Factor Stat="Charisma" Weight="2"/>
        <Factor Stat="Beauty" Weight="1"/>
        <Factor Stat="Agility" Weight="1"/>
        <Factor Stat="Confidence" Weight="1"/>
        <Factor Skill="Performance" Weight="2"/>

        <Mod>work.actress</Mod>

        <!-- This is currently handled on the C++ side -->
        <!-- Good -->
        <Trait Name="Charismatic" Value="30"/> <!-- Can act -->
        <Trait Name="Incorporeal" Value="20"/> <!-- Can't be hurt -->
        <Trait Name="Construct" Value="20"/>
        <Trait Name="Half-Construct" Value="15"/>
        <Trait Name="Muscular" Value="35"/>
        <Trait Name="Strong" Value="35"/>
        <Trait Name="Tough" Value="30"/>
        <Trait Name="Fleet of Foot" Value="30"/>
        <Trait Name="Agile" Value="30"/>
        <Trait Name="Heroine" Value="20"/> <!-- Exciting -->
        <Trait Name="Brawler" Value="20"/>
        <Trait Name="Dominatrix" Value="20"/>
        <Trait Name="Tsundere" Value="15"/>
        <Trait Name="Yandere" Value="15"/>
        <Trait Name="Fearless" Value="15"/>
        <Trait Name="Iron Will" Value="10"/>

        <!-- Bad -->
        <Trait Name="Fragile" Value="-30"/>    <!-- Tends to get hurt on set -->
        <Trait Name="Delicate" Value="-30"/>
        <Trait Name="Clumsy" Value="-10"/>
        <Trait Name="Dojikko" Value="-15"/>
    </Performance>

    <Gains XP="15" Skill="3">
        <Skill Name="Performance" Weight="4" Max="80"/>
        <Skill Name="Combat" Weight="1" Max="30"/>
        <Stat Name="Agility" Weight="2" Max="50" />
        <Stat Name="Confidence" Weight="1" Max="33" />

        <GainTrait Trait="Brawler" >
            <TraitChangeAmount Value="40" Chance="25">
                <TraitChangeCondition What="JobPerformance" Lower="140" Upper="200" />
            </TraitChangeAmount>
            <Text>She has performed in enough fight scenes that she has become quite a Brawler.</Text>
        </GainTrait>

        <GainTrait Trait="Tough" >
            <TraitChangeAmount Value="40" Chance="20">
                <TraitChangeCondition What="JobPerformance" Lower="150" Upper="200" />
                <TraitChangeCondition What="Strength" Lower="40" Upper="60" />
            </TraitChangeAmount>
            <Text>She has performed in enough fight scenes that she has become quite Tough.</Text>
        </GainTrait>

        <GainTrait Trait="Agile" >
            <TraitChangeAmount Value="40" Chance="15">
                <TraitChangeCondition What="JobPerformance" Lower="160" Upper="200" />
            </TraitChangeAmount>
            <Text>She has performed so many martial arts scenes that she is becoming agile.</Text>
        </GainTrait>

        <GainTrait Trait="Fleet of Foot" >
            <TraitChangeAmount Value="40" Chance="15">
                <TraitChangeCondition What="JobPerformance" Lower="160" Upper="200" />
            </TraitChangeAmount>
            <Text>She has performed so many action scenes that she has become fast on her feet.</Text>
        </GainTrait>

        <GainTrait Trait="Charismatic" >
            <TraitChangeAmount Value="40" Chance="40">
                <TraitChangeCondition What="JobPerformance" Lower="140" Upper="200" />
            </TraitChangeAmount>
            <Text>She has performed in enough movie scenes that she has become Charismatic.</Text>
        </GainTrait>

        <GainTrait Trait="Actress" >
            <TraitChangeAmount Value="40" Chance="50">
                <TraitChangeCondition What="JobPerformance" Lower="100" Upper="200" />
            </TraitChangeAmount>
            <Text>She has performed in enough movie scenes that she has become a good Actress.</Text>
        </GainTrait>

        <GainTrait Trait="Idol" >
            <TraitChangeAmount Value="75" Chance="20">
                <TraitChangeCondition What="JobPerformance" Lower="100" Upper="200" />
                <TraitChangeCondition What="Fame" Lower="50" Upper="100" />
            </TraitChangeAmount>
            <Text>Action hero ${name} has become an Idol, adored by her fans and followers.</Text>
        </GainTrait>

        <GainTrait Trait="Cool Person" >
            <TraitChangeAmount Value="40" Chance="33">
                <TraitChangeCondition What="JobPerformance" Lower="100" Upper="200" />
                <TraitChangeCondition What="Agility" Lower="33" Upper="66" />
            </TraitChangeAmount>
            <Text>Performing in action scenes makes ${name} a really Cool Person.</Text>
        </GainTrait>

        <GainTrait Trait="Sexy Air" >
            <TraitChangeAmount Value="40" Chance="25">
                <TraitChangeCondition What="JobPerformance" Lower="150" Upper="200" />
            </TraitChangeAmount>
            <Text>${name} has been having to be sexy for so long she now reeks Sexiness.</Text>
        </GainTrait>
    </Gains>

    <Messages>
        <Message Name="work">
            <Text>${name} worked as an actress in an action scene.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to shoot an action scene today.</Text>
        </Message>
        <Message Name="story">
            <Text>in which she battles a gang of demons.</Text>
            <Text>in which she defends a village against twisted, raping marauders.</Text>
            <Text>in which she avenges her mentor and defends her family's honour.</Text>
            <Text>in which she battles her evil step-brother for control of the Crimson Sceptre.</Text>
            <Text>in which she saves a twisted nunnery from the evil within.</Text>
            <Text>in which she opens hella whup-ass.</Text>
            <Text>in which she protects the Elven Princess from the Orc Prince's evil magics.</Text>
            <Text>in which she struggles to survive an island deathmatch sponsored by a corrupt state.</Text>
            <Text>in which she dies unfairly, and is forced to beat the Challenge of the Eight Divines to earn back her place among the living.</Text>
            <Text>in which she protects a handsome, kindly slave-master from his slaves' vicious mutiny.</Text>
            <Text>in which she is a bounty hunter, hunting down desperate criminals and dangerous escaped slaves.</Text>
            <Text>in which she battles her older sister who has been corrupted by the dark power of the Ninth Ward of Amocles.</Text>
            <Text>in which she is the last of a race of female warriors, taking vengeance against a dark Prince.</Text>
            <Text>in which she stars as a female monk defending a mountain temple from marauding Centaurs.</Text>
            <Text>in which she hunts down the sadistic pirate gang who kidnapped her sister.</Text>
        </Message>

        <Message Name="summary.like">
            <Text>She loved performing on film today.</Text>
        </Message>
        <Message Name="summary.neutral">
            <Text>She enjoyed this performance.</Text>
        </Message>
        <Message Name="summary.dislike">
            <Text>She found this awkward and did not enjoy it.</Text>
        </Message>
    </Messages>
</Job>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/MakePotions.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="MkPt">
    <Description>
        She will make various potions.
    </Description>

    <Performance>
        <Factor Skill="Brewing" Weight="3"/>
        <Factor Skill="Herbalism" Weight="3"/>
        <Factor Skill="Service" Weight="2"/>
        <Factor Skill="Magic" Weight="2"/>
        <Factor Skill="Cooking" Weight="2"/>

        <!-- good traits -->
        <Trait Name="Quick Learner" Value="5"/>
        <Trait Name="Psychic" Value="10"/>
        <Trait Name="Nerd" Value="10"/>

        <!-- bad traits -->
        <Trait Name="Dependent" Value="-50"/> <!-- needs others to do the job -->
        <Trait Name="Clumsy" Value="-20"/> <!-- spills food and breaks things often -->
        <Trait Name="Aggressive" Value="-20"/> <!-- gets mad easy -->
        <Trait Name="Nervous" Value="-30"/> <!-- don't like to be around people -->
        <Trait Name="Meek" Value="-20"/>
    </Performance>

    <Gains XP="10" Skill="3">
        <Skill Name="Brewing" Weight="3" />
        <Skill Name="Herbalism" Weight="3"/>
        <Skill Name="Cooking" Weight="1"/>
        <Skill Name="Magic" Weight="1"/>

        <LoseTrait Trait="Clumsy">
            <TraitChangeAmount Value="30" Chance="50" />
            <Text>It took her spilling hundreds of vials, and just as many reprimands,
                but ${name} has finally stopped being so Clumsy.</Text>
        </LoseTrait>

        <GainTrait Trait="Mixologist">
            <TraitChangeAmount Value="50" Chance="50">
                <TraitChangeCondition What="JobPerformance" Lower="150" Upper="200"/>
            </TraitChangeAmount>
            <Text>${name} has become an expert at Mixing potions.</Text>
        </GainTrait>
    </Gains>

    <Messages>
        <Message Name="work">
            <Text>${name} worked as a potions maker on the farm.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to brew potions during the ${shift} shift.</Text>
        </Message>
        <Message Name="repair">
            <Text>She spent some of her time repairing the Farm's equipment instead of making new stuff.</Text>
        </Message>
        <Message Name="produce">
            <Text>${name} made:</Text>
        </Message>
        <Include>DefaultPerformanceMessages.xml</Include>
    </Messages>
</Job>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/FilmChef.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="FChf">
    <Description>
        She will be filmed preparing food. And talking slowly. Sensuously. In sexy outfits. Because no reason.
    </Description>
    <Performance Modifier=".performance">
        <Factor Stat="Charisma" Weight="2"/>
        <Factor Stat="Beauty" Weight="1"/>
        <Factor Stat="Confidence" Weight="1"/>
        <Factor Skill="Performance" Weight="2"/>
        <Factor Skill="Cooking" Weight="1"/>

        <Mod>work.actress</Mod>

        <!-- good traits -->
        <Trait Name="Chef" Value="40"/>    <!-- Good at cooking -->
        <Trait Name="Mixologist" Value="20"/>  <!-- Good with measures -->
        <Trait Name="Charismatic" Value="25"/> <!-- Charisma on film -->
        <Trait Name="Sexy Air" Value="25"/>
        <Trait Name="Charming" Value="20"/>
        <Trait Name="Cool Person" Value="10"/>
        <Trait Name="Social Drinker" Value="5"/>   <!-- Drinks too -->
        <Trait Name="Exhibitionist" Value="30"/>   <!-- Shows off body -->
        <Trait Name="MILF" Value="15"/>    <!-- Attractive to some -->
        <Trait Name="Cute" Value="10"/>
        <Trait Name="Lolita" Value="10"/>
        <Trait Name="Elegant" Value="10"/>
        <Trait Name="Exotic" Value="5"/>
        <Trait Name="Beauty Mark" Value="5"/>
        <Trait Name="Fat" Value="10"/> <!-- Likes food -->
        <Trait Name="Plump" Value="5"/>
        <Trait Name="Wide Bottom" Value="5"/>
        <Trait Name="Plump Tush" Value="5"/>


        <!-- bad traits -->
        <Trait Name="Nervous" Value="-30"/>    <!-- weakens performance -->
        <Trait Name="Meek" Value="-20"/>
        <Trait Name="Shy" Value="-20"/>
        <Trait Name="One Arm" Value="-20"/>
        <Trait Name="One Hand" Value="-10"/>
        <Trait Name="No Arms" Value="-50"/>    <!-- hard to strip -->
        <Trait Name="No Hands" Value="-50"/>
        <Trait Name="Alcoholic" Value="-5"/>
    </Performance>

    <Gains XP="15" Skill="3">
        <Skill Name="Performance" Weight="2" />
        <Skill Name="Cooking" Weight="1" Max="50"/>
        <Stat Name="Charisma" Weight="1" />

        <GainTrait Trait="Actress" >
            <TraitChangeAmount Value="40" Chance="50">
                <TraitChangeCondition What="JobPerformance" Lower="100" Upper="200" />
            </TraitChangeAmount>
            <Text> Working on camera has improved her Acting skills.</Text>
        </GainTrait>

        <GainTrait Trait="Charming" >
            <TraitChangeAmount Value="40" Chance="33">
                <TraitChangeCondition What="JobPerformance" Lower="100" Upper="200" />
            </TraitChangeAmount>
            <Text>She has become quite Charming.</Text>
        </GainTrait>

        <GainTrait Trait="Chef" >
            <TraitChangeAmount Value="40" Chance="33">
                <TraitChangeCondition What="Cooking" Lower="40" Upper="80" />
            </TraitChangeAmount>
            <Text>${name} has become a competent Chef.</Text>
        </GainTrait>

        <GainTrait Trait="Sexy Air" >
            <TraitChangeAmount Value="40" Chance="25">
                <TraitChangeCondition What="JobPerformance" Lower="150" Upper="200" />
            </TraitChangeAmount>
            <Text>${name} has been having to be sexy for so long she now reeks Sexiness.</Text>
        </GainTrait>

        <GainTrait Trait="Idol" >
            <TraitChangeAmount Value="33" Chance="20">
                <TraitChangeCondition What="JobPerformance" Lower="100" Upper="200" />
                <TraitChangeCondition What="Fame" Lower="50" Upper="100" />
            </TraitChangeAmount>
            <Text>${name} has become an Idol, adored by her fans and followers.</Text>
        </GainTrait>
    </Gains>

    <Config PrimaryAction="Performing" SecondaryAction="Cooking">
    </Config>

    <Messages>
        <Message Name="work">
            <Text>${name} worked filming sexy chef scenes to educate and entertain viewers.</Text>
        </Message>
        <Message Name="refuse">
            <Text>${name} refused to make a kitchen show today.</Text>
        </Message>

        <Message Name="work.perfect">
            <Text>${name} created an outstanding show.
                She's so competent and flirtatious that the show is a hit with everyone.</Text>
        </Message>
        <Message Name="work.great">
            <Text>
                ${name} created a great show. Women are impressed with her competence.
                Men are impressed with her... competence. It doesn't hurt that she's hot and flirtatious.
            </Text>
        </Message>
        <Message Name="work.good">
            ${name} created a good show.
            <Text Condition="skill:Cooking>=stat:Beauty">Her skills in the kitchen are enough to carry the show.</Text>
            <Text Condition="skill:Cooking<=stat:Beauty">She's sexy enough that her fumbles in the kitchen go mostly unnoticed.</Text>
        </Message>
        <Message Name="work.ok">
            ${name} created an okay cooking show.
            <Text Condition="skill:Cooking>=stat:Beauty">She was skilled enough in the kitchen to mostly entertain.</Text>
            <Text Condition="skill:Cooking<=stat:Beauty">She's cute, so it doesn't really matter that she can't cook.</Text>
        </Message>
        <Message Name="work.bad">
            ${name} created a bad cooking show.
            <Text Condition="skill:Cooking>=stat:Beauty">The little skill she had in the kitchen wasn't nearly enough to save it.</Text>
            <Text Condition="skill:Cooking<=stat:Beauty">
                Perhaps if she'd quit breaking all the utensils and had instead taken her clothes off it would've been worth watching.
                Perhaps.
            </Text>
        </Message>
        <Message Name="work.worst">
            <Text>
                ${name} created a really bad cooking show.
                She had no charisma and burned or broke basically everything she touched. It was almost funny.
                Almost.
            </Text>
        </Message>
    </Messages>
</Job>

=== h1262216/crazys-wm-mod/Resources/Data/Jobs/FilmGroup.xml
<!DOCTYPE Job SYSTEM "job.dtd">
<Job ShortName="FGrp">
    <Description>
        She will film a group sex scene.
    </Description>

    <Config DefaultImage="Orgy" CanBeForced="1">
        <Enjoyment BaseEnjoyment="0" PrimaryAction="Fucking" SecondaryAction="Performing" />
        <Obedience Difficulty="30" Dignity="35" Fear="10" />
        <Pleasure Amount="25" SkillMin="33" BaseValue="15" Skill="Group"/>
    </Config>

    <Performance>
        <Factor Stat="Beauty" Weight="2"/>
        <Factor Stat="Charisma" Weight="1"/>
        <Factor Skill="Performance" Weight="2"/>
        <Factor Skill="Group" Weight="1"/>
        <Mod>work.pornstar</Mod>
    </Performance>

    <Gains XP="15" Skill="3">
        <Skill Name="Performance" Weight="2" />
        <Skill Name="Group" Weight="1" Max="50"/>
        <Stat Name="Constitution" Weight="1" Max="40"/>

        <GainTrait Trait="Porn Star" >
            <TraitChangeAmount Value="40" Chance="50">
                <TraitChangeCondition What="JobPerformance" Lower="100" Upper="200" />
            </TraitChangeAmount>
            <Text>She has performed in enough sex scenes that she has become a well known Porn Star.</Text>
        </GainTrait>

        <GainTrait Trait="Fake Orgasm Expert">
            <TraitChangeAmount Value="40" Chance="33">
                <TraitChangeCondition What="Libido" Lower="50" Upper="80" />
            </TraitChangeAmount>
            <Text>She has become quite the Faker.</Text>
        </GainTrait>

        <GainTrait Trait="Cum Addict" Event="2">
            <TraitChangeAmount Value="10" Chance="33">
                <TraitChangeCondition What="Libido" Lower="50" Upper="80" />
            </TraitChangeAmount>
            <Text>${name} has become addicted to Cum.</Text>
        </GainTrait>

        <GainTrait Trait="Slut" Event="2">
            <TraitChangeAmount Value="40" Chance="33">
                <TraitChangeCondition What="Libido" Lower="50" Upper="80" />
            </TraitChangeAmount>
            <Text>${name} has turned into quite a Slut.</Text>
        </GainTrait>

        <LoseTrait Trait="Chaste">
            <TraitChangeAmount Value="80" Chance="50" />
            <Text>She has been filmed having sex so often that she is no longer Chaste.</Text>
        </LoseTrait>
    </Gains>

    <Messages>
        <Message Name="work">
            <Text>${name} starred in an orgy scene today.</Text>
            <Text Condition="Nymphomaniac^Porn Star">
                ${name} worked in a scene where she tried to set a new record by taking part in a $[25|35|69] men gangbang.
            </Text>
        </Message>

        <Message Name="disobey.free">
            <Text>${name} refused to do an Orgy on film today.</Text>
        </Message>
        <Message Name="disobey.slave.nice">
            <Text>
                ${name} refused to do an Orgy on film today. Nice guy that you are, you let her be.
            </Text>
        </Message>
        <Message Name="disobey.slave.neutral">
            <Text>
                ${name} refused to perform in an Orgy scene today. "That's not how I wanted this to be," you say,
                "but I've got bills to pay. Boys, tie her up!" Seeing her terrified expression, you call out to her co-stars:
                "Be gentle with her, will ya!".
            </Text>
        </Message>
        <Message Name="disobey.slave.evil">
            <Text>
                "No, I'm not doing this!", ${name} complains. Ignoring her pleading, your men roughly tie her up.
                "It seems like a lesson in obedience is in order here", you say as you produce a pair of nipple clamps.
            </Text>
        </Message>

        <Message Name="pre-work-event">
            <Text Condition="Lolita" Chance="50">
                With such a young looking girl on the cover, this movie is simply sure to sell out.
            </Text>
            <Text Condition="Cute" Chance="50">
                Such a cute girl doing her best to handle the rough ponding her co-stars gave her will surely make a few hearts skip a beat.
            </Text>
            <Text Condition="Fragile|Delicate" Chance="50">
                This will be somewhat rough for her. Some people find that hot though.
            </Text>
        </Message>

        <Message Name="post-work-event">
            <Text Condition="Bimbo^Performance<150" Chance="50">
                Her performance couldn't be considered acting.
                She just enjoyed a good dicking with a blissfully stupid smile on her face.
            </Text>
            <Text Condition="Natural Pheromones" Chance="50">
                Her scent drove the actors mad with lust. They went at it harder and wilder than the director had ordered.
            </Text>
            <Text Condition="Fast Orgasms" Chance="50">
                She came the second she got two dicks inside her.
                That was the first of many orgasms.
                She barely remembered her own name by the end of the scene.
            </Text>
            <Text Condition="Great Arse" Chance="50">
                Her ass jiggling with each thrust was a sight to behold.
                The camera mage made sure to capture its wiggly glory in slow motion.
            </Text>
            <Text Condition="Plump" Chance="50">
                She sure offered a lot of meat to work with.
                The wet and fleshy sound she made with each thrust is sure to drive the audience wild.
            </Text>
            <Text Condition="Cum Addict" Chance="50">
                She insisted that her co-stars collect their semen in a cup for her to drink at the end of the scene.
            </Text>
            <Text Condition="Succubus" Chance="50">
                After the camera stopped running, she grabbed two actors and had another round with them.
            </Text>
        </Message>

        <Message Name="work.perfect">
            <Text>${name} filmed a perfect orgy scene.</Text>
        </Message>
        <Message Name="work.great">
            <Text>${name} filmed a great orgy scene.</Text>
        </Message>
        <Message Name="work.good">
            <Text>${name} did alright today, hopefully she will be better in the future.</Text>
        </Message>
        <Message Name="work.ok">
            <Text>The good thing about filming an orgy scene: Even if the main girl is rather unskilled,
                there is enough action going on for the end result to be decent. </Text>
        </Message>
        <Message Name="work.bad">
            <Text>${name} performed in an orgy scene. The result looked awful.</Text>
        </Message>
        <Message Name="work.worst">
            <Text>This has to be the worst orgy ever recorded on film.</Text>
        </Message>

        <Message Name="forced-filming">
            <Text Condition="Performance>100">
                Given ${name}'s rather 'unenthusiastic' performance, the scene turned out decent enough.
            </Text>
            <Text Condition="Performance<125^stat:Spirit<60">
                ${name} is just laying there, totally unresponsive except for a few whimpers and cries.
                Not a good scene.
            </Text>
            <Text Condition="Performance<125^stat:Spirit>=60">
                Despite being tied up, ${name} managed to hurt one of the other actors. Needless to say, the scene
                turned out rather bad.
            </Text>
            <Text Condition="Performance<50">
                While tying her up made it possible to film this scene, the result looks so bad that maybe you should
                have just sent her to the dungeon instead.
            </Text>
        </Message>
    </Messages>
</Job>
