=== h1262216/crazys-wm-mod/Resources/Data/Treatments/treatment.dtd
<!ELEMENT Treatment (Description, Config, Therapy?, Surgery?, Messages?)>
<!ATTLIST Treatment ShortName CDATA #REQUIRED>

<!ELEMENT Description (#PCDATA)>

<!ELEMENT Config (Filter)>
<!ATTLIST Config Shift (both|day-only|night-only|full) FreeOnly (0|1) #IMPLIED DefaultImage CDATA #IMPLIED
        Phase (prepare|produce|main|late) #IMPLIED FightingJob (0|1) #IMPLIED>
<!ELEMENT Filter (#PCDATA)>

<!ELEMENT Messages (Message|Include)*)>
<!ELEMENT Message ((Text|Group)+)>
<!ATTLIST Message Name CDATA #REQUIRED>
<!ELEMENT Text (#PCDATA)>
<!ATTLIST Text Condition CDATA #IMPLIED Priority CDATA #IMPLIED Chance CDATA #IMPLIED Updates CDATA #IMPLIED>
<!ELEMENT Group ((Text|Group)+)>
<!ATTLIST Group Condition CDATA #IMPLIED Priority CDATA #IMPLIED Chance CDATA #IMPLIED Updates CDATA #IMPLIED>

<!ELEMENT Include (#PCDATA)>

<!ELEMENT Therapy (RemoveTrait*)>
<!ATTLIST Therapy Duration CDATA #REQUIRED FightChance CDATA #REQUIRED Title CDATA #REQUIRED Title CDATA #REQUIRED SuccessBonus CDATA #REQUIRED HealthDanger CDATA #REQUIRED>

<!ELEMENT Surgery (TraitExclude*)>
<!ATTLIST Surgery Duration CDATA #REQUIRED>

<!ELEMENT TraitExclude (#PCDATA)>
<!ATTLIST TraitExclude Trait CDATA #REQUIRED>

<!ELEMENT RemoveTrait (#PCDATA)>
<!ATTLIST RemoveTrait Trait CDATA #REQUIRED>

=== h1262216/crazys-wm-mod/Resources/Data/Treatments/SoStraight.xml
<!DOCTYPE Treatment SYSTEM "treatment.dtd">
<Treatment Name="SO Straight" ShortName="SOSt">
    <Description>
        You will make sure she only likes having sex with men.
    </Description>

    <Config DefaultImage="Sex" Shift="full">
        <Filter>HouseTraining</Filter>
    </Config>

    <SexTraining TargetTrait="Straight" TargetName="Straight" />

    <Outcomes>
        <GainTrait Trait="Straight"/>
    </Outcomes>

    <Messages>
        <Message Name="training">
            <Text>You proceed to change ${name}'s sexual orientation to Straight.</Text>
        </Message>
        <Message Name="no-effect-possible">
            <Text>${name} is already Straight.</Text>
        </Message>
        <Message Name="no-mistress">
            <Text>There is no Mistress available to train ${name}.</Text>
        </Message>
        <Message Name="no-progress">
            <Text>She resisted all attempts to make her Straight.</Text>
        </Message>
        <Message Name="in-progress">
            <Text>Her Sexual Orientation conversion to Straight is in progress (${progress}).</Text>
        </Message>
        <Message Name="almost-done">
            <Text>Her Sexual Orientation conversion to Straight is almost complete.</Text>
        </Message>
        <Message Name="complete">
            <Text>Her Sexual Orientation conversion is complete. She is now Straight.</Text>
        </Message>

        <Message Name="dislikes-men">
            <Text>Her innate disgust of balls and shaft made her pull away from you while trying to teach her to suck it.</Text>
        </Message>
        <Message Name="broken-will">
            <Text>She just sits there doing exactly what you tell her to do.
                You don't think it is really getting through to her.</Text>
        </Message>
    </Messages>
</Treatment>

=== h1262216/crazys-wm-mod/Resources/Data/Treatments/Fertility.xml
<!DOCTYPE Treatment SYSTEM "treatment.dtd">
<Treatment Name="Fertility Treatment" ShortName="FrtT">
    <Description>
        She will undergo surgery to make her fertile.
        *(Takes up to 5 turns, less if a Nurse is on duty)
    </Description>

    <Surgery Duration="5">
        <TraitExclude Trait="Fertile">${name} is already as Fertile as she can be.</TraitExclude>
    </Surgery>

    <Messages>
        <Message Name="surgery">
            <Text>${name} is in the Clinic to get fertility treatment.</Text>
        </Message>

        <Message Name="doctor.work">
            <Text>Today, she worked on improving ${name}'s fertility.</Text>
        </Message>

        <Message Name="no-effect-possible">
            <Text>${name} is already a Broodmother, she cannot be more fertile.</Text>
        </Message>

        <Include>DefaultSurgeryMessages.xml</Include>
    </Messages>
</Treatment>

=== h1262216/crazys-wm-mod/Resources/Data/Treatments/AngerManagement.xml
<!DOCTYPE Treatment SYSTEM "treatment.dtd">
<Treatment Name="Anger Management" ShortName="AMng">
    <Description>
        She will go to anger management to get over her anger problems. (Aggressive, Tsundere, Yandere)
    </Description>

    <Therapy Duration="4" FightChance="20" Title="therapy" SuccessBonus="3">
    </Therapy>

    <Outcomes>
        <LoseTrait Trait="Aggressive">She is no longer Aggressive.</LoseTrait>
        <LoseTrait Trait="Tsundere">She is no longer a Tsundere.</LoseTrait>
        <LoseTrait Trait="Yandere">She is no longer a Yandere.</LoseTrait>
    </Outcomes>

    <Messages>
        <Message Name="therapy">
            <Text>${name} underwent therapy for anger issues.</Text>
        </Message>
        <Message Name="no-effect-possible">
            <Text>${name} doesn't need anger management.</Text>
        </Message>
        <Message Name="no-counselor">
            <Text>${name} has no counselor to help her with her anger issues.</Text>
        </Message>
        <Message Name="continue-therapy">
            <Text>She should stay in anger management to treat her other anger issues.</Text>
        </Message>
        <Message Name="death">
            <Text>She died in anger management.</Text>
        </Message>
        <Message Name="release">
            <Text>Her anger issues have been resolved, and she has been released from therapy.</Text>
        </Message>
    </Messages>
</Treatment>

=== h1262216/crazys-wm-mod/Resources/Data/Treatments/Rehab.xml
<!DOCTYPE Treatment SYSTEM "treatment.dtd">
<Treatment Name="Rehab" ShortName="Rehb" Title="Patient">
    <Description>
        She will go to rehab to get over her addictions.
    </Description>

    <Therapy Duration="6" FightChance="25" Title="rehab" SuccessBonus="8">
        <RemoveTrait Trait="Smoker">She is no longer a Smoker.</RemoveTrait>
        <RemoveTrait Trait="Cum Addict">She is no longer a Cum Addict.</RemoveTrait>
        <RemoveTrait Trait="Alcoholic">She is no longer an Alcoholic.</RemoveTrait>
        <RemoveTrait Trait="Fairy Dust Addict">She is no longer a Fairy Dust Addict.</RemoveTrait>
        <RemoveTrait Trait="Shroud Addict">She is no longer a Shroud Addict.</RemoveTrait>
        <RemoveTrait Trait="Viras Blood Addict">She is no longer a Viras Blood Addict.</RemoveTrait>
    </Therapy>

    <Messages>
        <Message Name="therapy">
            <Text>${name} was in rehab to get over her addiction.</Text>
        </Message>
        <Message Name="no-effect-possible">
            <Text>${name} is not addicted to anything.</Text>
        </Message>
        <Message Name="no-counselor">
            <Text>${name} sits in rehab doing nothing. You must assign a counselor to treat her.</Text>
        </Message>
        <Message Name="continue-therapy">
            <Text>She should stay in rehab to treat her other addictions.</Text>
        </Message>
        <Message Name="death">
            <Text>${name} died in rehab.</Text>
        </Message>
        <Message Name="release">
            <Text>She has mastered her addiction. She has been released from rehab.</Text>
        </Message>
    </Messages>
</Treatment>

=== h1262216/crazys-wm-mod/Resources/Data/Treatments/BoobJob.xml
<!DOCTYPE Treatment SYSTEM "treatment.dtd">
<Treatment Name="Boob Job" ShortName="BbJb" Title="Patient">
    <Description>
        She will undergo surgery to "enhance" her bust.
        *(Takes up to 3 turns per level, less if a Nurse is on duty)
    </Description>

    <Surgery Duration="3" />

    <Messages>
        <Message Name="surgery">
            <Text>${name} is in the Clinic to get her breasts enlarged.</Text>
        </Message>

        <Message Name="doctor.work">
            <Text>Today, she enhanced ${name}'s boobs.</Text>
        </Message>

        <Message Name="no-effect-possible">
            <Text>${name} already has Titanic Tits.</Text>
        </Message>

        <Include>DefaultSurgeryMessages.xml</Include>
    </Messages>
</Treatment>
